services:
  app_proxy:
    environment:
      APP_HOST: app
      APP_PORT: 3300
  app:
    image: ghcr.io/silver765/silvers-hw-monitor:1.4.0
    restart: unless-stopped
    volumes:
      - /sys/class/hwmon:/sys/class/hwmon:rw
      - /sys/class/thermal:/sys/class/thermal:rw
    cap_add:
      - SYS_RAWIO
    environment:
      PORT: "3300"
